# ---------- builder ----------
FROM --platform=linux/arm64 golang:1.25-alpine AS builder

WORKDIR /app

# Copiar módulos primero
COPY go.mod go.sum ./
RUN go mod download

# Copiar el código
COPY . .

# Compilar binario ARM64
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o app ./cmd/server

# ---------- runtime ----------
FROM --platform=linux/arm64 alpine:3.22

WORKDIR /app

COPY --from=builder /app/app /app/app

EXPOSE 8080

ENTRYPOINT ["/app/app"]
