FROM golang:1.25-alpine

RUN apk add --no-cache git bash

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go install github.com/go-delve/delve/cmd/dlv@latest

EXPOSE 8080 2345
CMD ["dlv", "debug", "./cmd/server", "--headless", "--listen=0.0.0.0:2345", "--api-version=2"]
